---
## Author
author:
  name: Ванюшкина Татьяна Валерьевна
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 1132246713@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "отчет по лабораторной работе 1"
subtitle: "Установка и конфигурация
операционной системы на виртуальную машину"
license: "CC BY"
---

# Цель работы

Целью данной работы является приобретение практических навыков
установки операционной системы на виртуальную машину, настройки ми-
нимально необходимых для дальнейшей работы сервисов.
# Задание

Установить операционную систему на виртуальную машину

# Выполнение лабораторной работы                       

Загружаю в дисплейном классе операционную систему Linux.
Осуществляю вход в систему. 
Запускаю терминал. Перехожу в каталог /var/tmp:
cd /var/tmp
Создаю каталог с именем пользователя 
Запустите виртуальную машину         
Создаю новую виртуальную машину, задаю необходимые параметры
Получаю полномочия администратора
Устанавливаю имя хоста 
Дождаюсь загрузки графического окружения и открываю терминал. В окне
терминала анализирую  последовательность загрузки системы, выпол-
нив команду dmesg.                                                 |
[1](image/1.jpg){#fig-001 width=70%}

# Выводы

Я установила операционную систему на виртуальную машину

# Список литературы{.unnumbered}

::: {#refs}
:::
