---
## Author
author:
  name: Ванюшкина Татьяна Валерьевна
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: 11322466713@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "отчёт по лабораторной работе"
subtitle: "лабораторная робота номер 6"
license: "CC BY"
---

# Цель работы

- Развить навыки администрирования ОС Linux. Получить первое прак-тическое знакомство с технологией SELinux1.
- Проверить работу SELinx на практике совместно с веб-серверо Apache.
## Материалы и методы


# Выполнение лабораторной работы
1. Входу  в систему с полученными учётными данными и убедитесь, что
SELinux работает в режиме enforcing политики targeted с помощью ко-
манд getenforce и sestatus.
2. Обращаюсь с помощью браузера к веб-серверу, запущенному на вашем
компьютере, и убедитесь, что последний работает:
service httpd status
или
/etc/rc.d/init.d/httpd statu

3. Нахожу веб-сервер Apache в списке процессов, определите его контекст
безопасности и занесите эту информацию в отчёт. Например, можно ис-
пользовать команду
ps auxZ | grep httpd
или
ps -eZ | grep httpd
4. Смотрю текущее состояние переключателей SELinux для Apache с
помощью команды
sestatus -bigrep httpd
Обратите внимание, что многие из них находятся в положении «off»

5. Смотрю статистику по политике с помощью команды seinfo, также
определите множество пользователей, ролей, типов.
6. Определяю тип файлов и поддиректорий, находящихся в директории
/var/www, с помощью команды
ls -lZ /var/www
7. Определяю тип файлов, находящихся в директории /var/www/html:
ls -lZ /var/www/html
8. Определяю круг пользователей, которым разрешено создание файлов в
директории /var/www/html.

9. Создаю от имени суперпользователя (так как в дистрибутиве по-
сле установки только ему разрешена запись в директорию) html-файл
/var/www/html/test.html следующего содержания:
<html>
<body>test</body>
</html>
10. Проверяю контекст созданного вами файла. Занесите в отчёт контекст,
присваиваемый по умолчанию вновь созданным файлам в директории
/var/www/html.
11. Обращаюсь к файлу через веб-сервер, введя в браузере адрес
http://127.0.0.1/test.html. Убедитесь, что файл был успеш-
но отображён.

12. Изучаю  справку man httpd_selinux и выясните, какие контек-
сты файлов определены для httpd. Сопоставьте их с типом файла
test.html. Проверить контекст файла можно командой ls -Z.
ls -Z /var/www/html/test.html

Изменяю контекст файла /var/www/html/test.html с
httpd_sys_content_t на любой другой, к которому процесс httpd не
должен иметь доступа, например, на samba_share_t:
chcon -t samba_share_t /var/www/html/test.html
ls -Z /var/www/html/test.html
После этого проверяю, что контекст поменялся.
14. Пробую ещё раз получить доступ к файлу через веб-сервер, введя в
браузере адрес http://127.0.0.1/test.html. Вы должны получить
сообщение об ошибке:
Forbidden
You don't have permission to access /test.html on this server.

15. Анализирую ситуацию. Почему файл не был отображён, если права
доступа позволяют читать этот файл любому пользователю?
ls -l /var/www/html/test.html
Смотрю log-файлы веб-сервера Apache. Также просмотрите си-
стемный лог-файл:
tail /var/log/messages
Если в системе окажутся запущенными процессы setroubleshootd и
audtd, то вы также сможете увидеть ошибки, аналогичные указанным
выше, в файле /var/log/audit/audit.log. Проверьте это утвержде-
ние самостоятельно.
16. Пробую запустить веб-сервер Apache на прослушивание ТСР-порта
81 (а не 80, как рекомендует IANA и прописано в /etc/services). Для
этого в файле /etc/httpd/httpd.conf найдите строчку Listen 80 и
замените её на Listen 81.

## 8

17. Выполняю перезапуск веб-сервера Apache. 
19. Выполняюе команду
semanage port -a -t http_port_t -р tcp 81
После этого проверьте список портов командой
semanage port -l | grep http_port_t
Убедитесь, что порт 81 появился в списке.

20. Попробую запустить веб-сервер Apache ещё раз. 
22. Исправляю обратно конфигурационный файл apache, вернув Listen 80.
23. Удаляю привязку http_port_t к 81 порту:
semanage port -d -t http_port_t -p tcp 81
и проверьтые, что порт 81 удалён.
24. Удалите файл /var/www/html/te

# Выводы

- Развить навыки администрирования ОС Linux. Получить первое прак-тическое знакомство с технологией SELinux1.
- Проверить работу SELinx на практике совместно с веб-серверо Apache.
## Материалы и методы

# Список литературы{.unnumbered}

::: {#refs}
:::
