---
## Author
author:
  name: Ванюшкина Татьяна Валерьевна
  degrees: DSc
  orcid: 0000-0002-0877-7063
  email: kulyabov-ds@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: " отчёт по лабораторной работе"
subtitle: "отчет по лабораторной работе 7"
license: "CC BY"
---

# Цель работы


Освоить на практике применение режима однократного программирования
# Задание

Здесь приводится описание задания в соответствии с рекомендациями методического пособия и выданным вариантом.

# Теоретическое введение

Предложенная Г. С. Вернамом так называемая «схема однократного ис-
пользования (гаммирования)» (рис. 7.1) является простой, но надёжной схе-
мой шифрования данных.
Гаммирование представляет собой наложение (снятие) на открытые (за-
шифрованные) данные последовательности элементов других данных, по-
лученной с помощью некоторого криптографического алгоритма, для по-
лучения зашифрованных (открытых) данных. Иными словами, наложение
гаммы — это сложение её элементов с элементами открытого (закрытого)
текста по некоторому фиксированному модулю, значение к

# Выполнение лабораторной работы

1. Определяю вид шифротекста при известном ключе и известном откры-
том тексте.
2. Определяю ключ, с помощью которого шифротекст может быть преоб-
разован в некоторый фрагмент текста, представляющий собой один из
возможных вариантов прочтения открытого текста.


# Выводы

я освоила применение режима однократного программирования

# Список литературы{.unnumbered}

::: {#refs}
:::
